import React from 'react'
import { useResource } from 'frontend-js'
import { useAdmin } from '../../hooks'

const useOrders = () => {
	const { apiUrl } = useAdmin()

	const {
		loading,
		delayedLoading,
		loaded,
		errors,
		empty,
		editing,
		isValid,
		resource: order,
		resources: orders,
		findOne: findOrder,
		findMany: findOrders,
		update: updateOrder,
		updateMany: updateOrders,
		create: createOrder,
		save: saveOrder,
		destroy: deleteOrder,
		deleteMany: deleteOrders,
		loadMore,
		publish,
		unpublish,
		handleChange,
		handleChangePage,
		updatePositions,
		addAttachment,
		removeAttachment,
		query,
		setQuery,
		page,
		numPages,
		perPage,
		totalCount,
		sortBy,
		sortDirection,
		handleSort,
		reloadOne: reloadOrder,
		reloadMany: reloadOrders,
		setResource: setOrder,
		setResources: setOrders,
		startIndex,
		endIndex,
		paginate,
	} = useResource({
		url: `${apiUrl}/orders`,
		name: 'order',
	})

	return {
		paginate,
		loading,
		loaded,
		delayedLoading,
		errors,
		empty,
		editing,
		isValid,
		order,
		orders,
		findOrder,
		findOrders,
		saveOrder,
		updateOrder,
		updateOrders,
		createOrder,
		deleteOrder,
		deleteOrders,
		loadMore,
		publish,
		unpublish,
		addAttachment,
		removeAttachment,
		handleChange,
		handleChangePage,
		query,
		setQuery,
		reloadOrder,
		reloadOrders,
		page,
		numPages,
		perPage,
		totalCount,
		updatePositions,
		sortBy,
		sortDirection,
		handleSort,
		setOrder,
		setOrders,
		startIndex,
		endIndex,
	}
}

export default useOrders
